
services:
  redis:
    image: redis:7-alpine
    networks:
      - internal
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 256M

  api:
    build: ./api
    depends_on:
      redis:
        condition: service_healthy
    environment:
       REDIS_HOST: ${REDIS_HOST}
       REDIS_PORT: ${REDIS_PORT}
    networks:
      - internal
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M

  worker:
    build: ./worker
    depends_on:
      redis:
        condition: service_healthy
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    networks:
      - internal
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
  frontend:
    build: ./frontend
    depends_on:
      api:
        condition: service_healthy
    environment:
      PORT: 3000
      API_URL: ${API_URL}
    ports:
      - "3000:3000"
    networks:
      - internal
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M

networks:
  internal:
    driver: bridge